const userLang = navigator.language.substring(0, 2);
const supportedLangs = ['ko', 'en', 'ja', 'zh', 'es', 'pt', 'hi'];
const LANG = supportedLangs.includes(userLang) ? userLang : 'en';

const SYSTEM_PROMPTS = {
    ko: "한국어로 답변하세요.",
    en: "Respond in English.",
    ja: "日本語で答えてください。",
    zh: "请用中文回答。",
    es: "Responde en español.",
    pt: "Responda em português.",
    hi: "हिंदी में उत्तर दें।"
};

const T_DATA = {
    en: {
        welcome: "How can I help you?", 
        ph_chat: "Ask AI anything...", 
        ph_search: "Search topic...", 
        ph_image: "Describe image...", 
        ph_video: "Describe the video scene...",
        ph_music: "Describe the music...", 
        ph_blog: "Enter a topic for the blog post...", 
        ph_app: "Search Shortcuts...", 
        ph_code: "Request Code...",
        ph_search_store: "Search apps...", 
        popup_title_limit: "Limit Reached", 
        popup_msg_limit: "Daily limit reached.",
        popup_title_wifi: "Offline Mode", 
        popup_msg_wifi: "Continue in Offline Mode (~600MB)", 
        btn_cancel: "Cancel", 
        btn_confirm: "Download", 
        error: "Error",
        local_on: "Offline Mode On", 
        local_off: "Offline Mode Off", 
        no_apps: "No apps found.",
        code_copied: "Code Copied!"
    },
    ko: {
        welcome: "무엇을 도와드릴까요?", 
        ph_chat: "AI에게 물어보세요...", 
        ph_search: "검색할 주제를 입력하세요...", 
        ph_image: "이미지를 묘사하세요...", 
        ph_video: "비디오 장면을 묘사하세요...",
        ph_music: "음악을 묘사하세요...", 
        ph_blog: "블로그 포스트 주제를 입력하세요...", 
        ph_app: "바로가기 검색...", 
        ph_code: "코드를 요청하세요...",
        ph_search_store: "앱 검색...", 
        popup_title_limit: "한도 초과", 
        popup_msg_limit: "일일 사용 한도 초과.",
        popup_title_wifi: "오프라인 모드", 
        popup_msg_wifi: "오프라인 모드로 계속 (~600MB)", 
        btn_cancel: "취소", 
        btn_confirm: "다운로드", 
        error: "오류 발생",
        local_on: "오프라인 모드 켜짐", 
        local_off: "오프라인 모드 꺼짐", 
        no_apps: "검색된 앱이 없습니다.",
        code_copied: "코드 복사완료!"
    },
    ja: {
        welcome: "何かお手伝いしましょうか？", 
        ph_chat: "AIに何か聞く...", 
        ph_search: "トピックを検索...", 
        ph_image: "画像を説明...", 
        ph_video: "動画のシーンを説明...",
        ph_music: "音楽を説明...", 
        ph_blog: "ブログ記事のトピックを入力...", 
        ph_app: "ショートカットを検索...", 
        ph_code: "コードをリクエスト...",
        ph_search_store: "アプリを検索...", 
        popup_title_limit: "制限到達", 
        popup_msg_limit: "1日の使用制限に達しました。",
        popup_title_wifi: "オフラインモード", 
        popup_msg_wifi: "オフラインモードで続ける (~600MB)", 
        btn_cancel: "キャンセル", 
        btn_confirm: "ダウンロード", 
        error: "エラー",
        local_on: "オフラインモード オン", 
        local_off: "オフラインモード オフ", 
        no_apps: "アプリが見つかりません。",
        code_copied: "コードをコピーしました！"
    },
    zh: {
        welcome: "我能为您做些什么？", 
        ph_chat: "询问AI...", 
        ph_search: "搜索主题...", 
        ph_image: "描述图片...", 
        ph_video: "描述视频场景...",
        ph_music: "描述音乐...", 
        ph_blog: "输入博客文章主题...", 
        ph_app: "搜索快捷方式...", 
        ph_code: "请求代码...",
        ph_search_store: "搜索应用...", 
        popup_title_limit: "达到限制", 
        popup_msg_limit: "已达到每日使用限制。",
        popup_title_wifi: "离线模式", 
        popup_msg_wifi: "继续离线模式 (~600MB)", 
        btn_cancel: "取消", 
        btn_confirm: "下载", 
        error: "错误",
        local_on: "离线模式已开启", 
        local_off: "离线模式已关闭", 
        no_apps: "未找到应用。",
        code_copied: "代码已复制！"
    },
    es: {
        welcome: "¿Cómo puedo ayudarte?", 
        ph_chat: "Pregunta a la IA...", 
        ph_search: "Buscar tema...", 
        ph_image: "Describir imagen...", 
        ph_video: "Describir escena de video...",
        ph_music: "Describir música...", 
        ph_blog: "Introduce un tema para el blog...", 
        ph_app: "Buscar accesos...", 
        ph_code: "Solicitar código...",
        ph_search_store: "Buscar aplicaciones...", 
        popup_title_limit: "Límite alcanzado", 
        popup_msg_limit: "Límite diario alcanzado.",
        popup_title_wifi: "Modo sin conexión", 
        popup_msg_wifi: "Continuar en modo sin conexión (~600MB)", 
        btn_cancel: "Cancelar", 
        btn_confirm: "Descargar", 
        error: "Error",
        local_on: "Modo sin conexión activado", 
        local_off: "Modo sin conexión desactivado", 
        no_apps: "No se encontraron aplicaciones.",
        code_copied: "¡Código copiado!"
    },
    pt: {
        welcome: "Como posso ajudar?", 
        ph_chat: "Pergunte à IA...", 
        ph_search: "Pesquisar tópico...", 
        ph_image: "Descrever imagem...", 
        ph_video: "Descrever cena do vídeo...",
        ph_music: "Descrever música...", 
        ph_blog: "Digite um tópico para o post do blog...", 
        ph_app: "Pesquisar atalhos...", 
        ph_code: "Solicitar código...",
        ph_search_store: "Pesquisar aplicativos...", 
        popup_title_limit: "Limite atingido", 
        popup_msg_limit: "Limite diário atingido.",
        popup_title_wifi: "Modo Offline", 
        popup_msg_wifi: "Continuar no modo offline (~600MB)", 
        btn_cancel: "Cancelar", 
        btn_confirm: "Baixar", 
        error: "Erro",
        local_on: "Modo Offline Ativo", 
        local_off: "Modo Offline Desativado", 
        no_apps: "Nenhum aplicativo encontrado.",
        code_copied: "Código copiado!"
    },
    hi: {
        welcome: "मैं आपकी कैसे मदद कर सकता हूँ?", 
        ph_chat: "AI से कुछ भी पूछें...", 
        ph_search: "विषय खोजें...", 
        ph_image: "छवि का वर्णन करें...", 
        ph_video: "वीडियो दृश्य का वर्णन करें...",
        ph_music: "संगीत का वर्णन करें...", 
        ph_blog: "ब्लॉग पोस्ट के लिए विषय दर्ज करें...", 
        ph_app: "शॉर्टकट खोजें...", 
        ph_code: "कोड का अनुरोध करें...",
        ph_search_store: "ऐप्स खोजें...", 
        popup_title_limit: "सीमा समाप्त", 
        popup_msg_limit: "दैनिक सीमा समाप्त हो गई है।",
        popup_title_wifi: "ऑफ़लाइन मोड", 
        popup_msg_wifi: "ऑफ़लाइन मोड जारी रखें (~600MB)", 
        btn_cancel: "रद्द करें", 
        btn_confirm: "डाउनलोड", 
        error: "त्रुटि",
        local_on: "ऑफ़लाइन मोड चालू", 
        local_off: "ऑफ़लाइन मोड बंद", 
        no_apps: "कोई ऐप्स नहीं मिले।",
        code_copied: "कोड कॉपी किया गया!"
    }
};

const T = T_DATA[LANG];